/* https://www.hackerrank.com/challenges/placements/problem?isFullScreen=true */
/* Placements MediumSQL (Intermediate) */ 
SELECT NAME FROM
(SELECT E.ID , E.NAME , E.FRIEND_ID , E.SALARY PERSONS, F.SALARY FRIEND FROM
(SELECT C.ID , C.NAME , C.FRIEND_ID , D.SALARY FROM
(SELECT A.ID , A.NAME , B.FRIEND_ID FROM STUDENTS A INNER JOIN FRIENDS B ON A.ID=B.ID)C INNER JOIN PACKAGES D ON C.ID=D.ID)E
INNER JOIN PACKAGES F ON F.ID=E.FRIEND_ID)G
WHERE G.FRIEND > G.PERSONS
ORDER BY G.FRIEND
